#+TITLE: Installing Conkeror web browser on Ubuntu

** Introduction

These are my notes for building [[http://conkeror.org/][Conkeror]] from source on Ubuntu. 
There are probably other ways to install on Ubuntu but I prefer to build, 
as if I need to patch the source I can easily.

Conkeror is a keyboard-oriented, highly-customizable, highly-extensible web browser 
based on Mozilla XULRunner, written mainly in JavaScript, and inspired by Emacs.

** Installation

You can download the lastest git version of Conkeror from the git repository 
=http://repo.or.cz/r/conkeror.git=.

From the command line I install like this...

Download source:

#+begin_src sh   :lang bash
mkdir -p ~/Builds/conkeror_build
cd ~/Builds/conkeror_build
git clone http://repo.or.cz/r/conkeror.git
cd conkeror
#+end_src sh   :lang bash

Build source:

#+begin_src sh   :lang bash
make
sudo make install
#+end_src sh   :lang bash
** Post Installation

To configure Conkeror you can put your configuration in a file called 
=.conkerorrc= or you can split your config files in a 
=/.conkerorrc= directory.

I setup my Conkeror config from my Github repo like this:
#+begin_src sh   :lang bash
git clone https://github.com/draganvu/conkeror-config.git ~/.conkerorrc
#+end_src sh   :lang bash
